# BEGIN_KITTY_THEME
# Atelier Cave Dark
include current-theme.conf
include ~/.cache/wal/colors-kitty.conf
# END_KITTY_THEME

#Font config
font_family Departure Mono
font_size 10.0

#Window layout
window_padding_width 10
remember_window_size no
intial_window_width 900
initial_window_height 600

#Performance and Behavior
confirm_os_window_close 0
