# Shell variables
# Generated by 'wal'
wallpaper="/home/garrett/Pictures/wallpapers/wallpaper6.jpg"

# Special
background='#141430'
foreground='#c4c4cb'
cursor='#c4c4cb'

# Colors
color0='#141430'
color1='#5C68CF'
color2='#9B65A9'
color3='#9F74CD'
color4='#6F8EE4'
color5='#EBA7AF'
color6='#A199DD'
color7='#c4c4cb'
color8='#63637a'
color9='#5C68CF'
color10='#9B65A9'
color11='#9F74CD'
color12='#6F8EE4'
color13='#EBA7AF'
color14='#A199DD'
color15='#c4c4cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
