foreground         #c4c4cb
background         #141430
background_opacity 1.0
cursor             #c4c4cb

active_tab_foreground     #141430
active_tab_background     #c4c4cb
inactive_tab_foreground   #c4c4cb
inactive_tab_background   #141430

active_border_color   #c4c4cb
inactive_border_color #141430
bell_border_color     #5C68CF

color0       #141430
color8       #63637a
color1       #5C68CF
color9       #5C68CF
color2       #9B65A9
color10      #9B65A9
color3       #9F74CD
color11      #9F74CD
color4       #6F8EE4
color12      #6F8EE4
color5       #EBA7AF
color13      #EBA7AF
color6       #A199DD
color14      #A199DD
color7       #c4c4cb
color15      #c4c4cb
